phantomjs:
  build: .
  command: bundle exec cucumber -p poltergeist -f pretty
  volumes:
    - .:/myapp
  ports:
    - "4777:4777"

safari-browserstack:
  build: .
  command: bundle exec cucumber -p browserstack -f pretty
  volumes:
    - .:/myapp

ie-sauce:
  build: .
  command: bundle exec cucumber -p sauce -f pretty
  volumes:
    - .:/myapp
